import os
import sys
import unittest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src"))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from openskill.apifinder.index import load_index, search


class CatalogTests(unittest.TestCase):
    def test_catalog_covers_supported_core_surface(self):
        entries = load_index()
        symbols = {entry["symbol"] for entry in entries}
        self.assertGreaterEqual(len(entries), 195)
        for required in {
            "quote",
            "quasiquote",
            "if",
            "cond",
            "caseq",
            "and",
            "or",
            "prog",
            "prog1",
            "prog2",
            "return",
            "catch",
            "throw",
            "procedure",
            "lambda",
            "defun",
            "defmacro",
            "nprocedure",
            "mprocedure",
            "for",
            "foreach",
            "while",
            "apply",
            "funcall",
            "eval",
            "symeval",
            "getd",
            "putd",
            "makunbound",
            "remd",
            "gensym",
            "intern",
            "symbolName",
            "mapcar",
            "map",
            "mapc",
            "maplist",
            "mapcan",
            "mapcon",
            "mapinto",
            "setof",
            "exists",
            "forall",
            "sort",
            "sortcar",
            "type",
            "reverse",
            "append1",
            "caar",
            "cdar",
            "cddr",
            "caadr",
            "copy",
            "copylist",
            "memq",
            "assq",
            "lindex",
            "nthcdr",
            "nthelem",
            "remove",
            "remq",
            "remd",
            "remdq",
            "nconc",
            "rplaca",
            "rplacd",
            "tailp",
            "subst",
            "plist",
            "setplist",
            "get",
            "putprop",
            "remprop",
            "integerp",
            "fixp",
            "floatp",
            "zerop",
            "plusp",
            "minusp",
            "evenp",
            "oddp",
            "onep",
            "sprintf",
            "concat",
            "strlen",
            "strcmp",
            "alphalessp",
            "substr",
            "substring",
            "getchar",
            "index",
            "rindex",
            "nindex",
            "upperCase",
            "lowerCase",
            "buildString",
            "parseString",
            "rexCompile",
            "rexExecute",
            "rexMatchp",
            "rexReplace",
            "rexSubstitute",
            "add1",
            "sub1",
            "round",
            "exp",
            "log",
            "sqrt",
            "sin",
            "cos",
            "tan",
            "asin",
            "acos",
            "atan",
            "random",
            "srandom",
            "array",
            "arrayref",
            "setarray",
            "arrayp",
            "makeTable",
            "put",
            "tablep",
            "infile",
            "outfile",
            "instring",
            "outstring",
            "getOutstring",
            "close",
            "lineread",
            "gets",
            "getc",
            "fprintf",
            "loadi",
            "loadstring",
            "evalstring",
            "macroexpand",
            "getWarn",
            "plus",
            "difference",
            "times",
            "quotient",
            "warn",
            "error",
            "errset",
            "+",
            ">=",
            "printf",
        }:
            self.assertIn(required, symbols)

    def test_search_uses_catalog_as_single_source_of_truth(self):
        results = search("quasiquote")
        self.assertTrue(results)
        self.assertEqual(results[0]["symbol"], "quasiquote")


if __name__ == "__main__":
    unittest.main()
